/**
 * Output writers — inline JS module + per-key R2 blob directory.
 *
 * The bundler doesn't push to R2 itself; it writes the blobs to a local
 * directory and emits a manifest. A separate step (e.g. `kb-bundler
 * upload-r2 <manifest>`) actually uploads.
 */
const fs = require("node:fs");
const path = require("node:path");
const { bytes } = require("./helpers");

class R2Writer {
  constructor(outDir) {
    this.outDir = outDir;
    this.objects = []; // [{key, bytes, content_type}]
    fs.mkdirSync(outDir, { recursive: true });
  }

  /** key: object key (no leading slash). content: string | object. */
  write(key, content, content_type) {
    if (key.startsWith("/")) throw new Error(`R2 key must not start with /: ${key}`);
    const isObj = typeof content !== "string";
    const data = isObj ? JSON.stringify(content) : content;
    const ct = content_type || (isObj ? "application/json" : "text/plain");
    const fullPath = path.join(this.outDir, key);
    fs.mkdirSync(path.dirname(fullPath), { recursive: true });
    fs.writeFileSync(fullPath, data, "utf8");
    this.objects.push({ key, bytes: bytes(data), content_type: ct });
  }

  totalBytes() {
    return this.objects.reduce((s, o) => s + o.bytes, 0);
  }

  count() {
    return this.objects.length;
  }
}

/**
 * Write an ES module file with the given exports.
 *   exports: { NAME: value, ... }   (each value JSON-serializable)
 *   header:  optional string written as a top-of-file comment
 */
function writeInlineModule(outFile, exportsMap, header = "") {
  fs.mkdirSync(path.dirname(outFile), { recursive: true });
  const headerLines = [
    `// AUTO-GENERATED by @mscrnt/kb-bundler — do not edit by hand.`,
    `// Built ${new Date().toISOString()}.`,
  ];
  if (header) {
    for (const ln of header.split("\n")) headerLines.push(`// ${ln}`);
  }
  const body = [
    headerLines.join("\n"),
    "",
    `export const BUILD_STAMP = ${JSON.stringify(new Date().toISOString())};`,
    "",
  ];
  for (const [name, value] of Object.entries(exportsMap)) {
    if (!/^[A-Z][A-Z0-9_]*$/.test(name)) {
      throw new Error(`Inline export name must be SCREAMING_SNAKE_CASE: ${name}`);
    }
    body.push(`export const ${name} = ${JSON.stringify(value)};`);
  }
  const out = body.join("\n") + "\n";
  fs.writeFileSync(outFile, out, "utf8");
  return bytes(out);
}

module.exports = { R2Writer, writeInlineModule };
